name: absensi
description: Aplikasi Smart Geo-Attendance UAS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  camera: ^0.11.0
  http: ^1.1.0
  path_provider: ^2.1.5
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  table_calendar: ^3.2.0
  supabase_flutter: ^2.5.0
  dio: ^5.9.0
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logobiru.png